openapi: 3.0.0
info:
  title: Chat API
  description: MVP чата-хаба на userver
  version: 1.0.0
servers:
  - url: /v1
    description: Основной шлюз API

tags:
  - name: Auth
    description: Аутентификация и регистрация
  - name: Users
    description: Управление пользователями
  - name: Messages
    description: Отправка и получение сообщений
  - name: Chats
    description: (Пока не используется)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Error
    Error:
      type: object
      properties:
        code:
          type: string
          example: "400"
        message:
          type: string
          example: "Неверное имя пользователя или пароль"
        details:
          type: object
          properties:
            errors:
              type: object
              description: Ошибки валидации по полям
              additionalProperties:
                type: array
                items:
                  type: string
    # Token
    AuthToken:
      type: object
      required:
        - access-token
      properties:
        access-token:
          type: string
          format: jwt
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

    # Users
    UserRegistrationRequest:
      type: object
      additionalProperties: false
      required: [user]
      properties:
        user:
          type: object
          additionalProperties: false
          required: [username, password, display_name]
          properties:
            username:
              type: string
              minLength: 3
              maxLength: 32
            password:
              type: string
              minLength: 8
              format: password
            display_name:
              type: string
              minLength: 3
              maxLength: 50
            biography:
              type: string
              maxLength: 180

    UserLoginRequest:
      type: object
      additionalProperties: false
      required: [username, password]
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 32
        password:
          type: string
          minLength: 8
          format: password

    UserRegistered:
      type: object
      properties:
        username:
          type: string
          example: alice
        token:
          $ref: "#/components/schemas/AuthToken"

    UserProfile:
      type: object
      properties:
        username:
          type: string
          example: alice
        display_name:
          type: string
          example: "Daniil Repin"
        biography:
          type: string
          example: "My biography"
    
    # Messages
    SendMessageRequest:
      type: object
      description: Сообщение для отправки
      properties:
        recipient-username:
          type: string
          description: Username пользователя, которому отправляется сообщение
        payload:
          type: string
          description: Текст сообщения
          example: "Hello, World!"
      required:
        - recipient-username
        - payload

paths:
  # Users
  /users/register:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
      responses:
        "200":
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegistered"
        "400":
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Пользователь с таким именем уже существует
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/login:
    post:
      tags:
        - Auth
      summary: Вход пользователя (получение токена)
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
      responses:
        "200":
          description: Успешный вход, токен выдан
          content:
            application/json:
              schema:
                type: string
                format: JWT
                example: "eyJhbGciO.iJIUzI1NiIsI.nR5cCI6IkpXVCJ9"
        "400":
          description: Неверные входные параметры
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Не авторизован

  /users/username/{username}:
    get:
      tags:
        - Users
      summary: Получение профиля пользователя по username
      operationId: getUserProfileByUsername
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Профиль получен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Не авторизован
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/id/{user_id}:
    get:
      tags:
        - Users
      summary: Получение профиля пользователя по user_id
      description: Получить публичный профиль пользователя по его уникальному идентификатору.
      operationId: getUserProfileById
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Профиль получен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  # Messages
  /messages/send:
    post:
      tags:
        - Messages
      summary: Отправить сообщение пользователю
      operationId: sendMessage
      security:
        - BearerAuth: []
      requestBody:
        description: Сообщение для отправки
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
      responses:
        "202":
          description: Сообщение принято к доставке
        "400":
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Не авторизован
        "404":
          description: Получатель не найден
        "409":
          description: Пользователь офлайн