openapi: 3.0.0
info:
  title: Chat API
  description: MVP чата-хаба на userver
  version: 1.0.0
servers:
  - url: /v1
    description: Основной шлюз API

tags:
  - name: Auth
    description: Аутентификация и регистрация
  - name: Users
    description: Управление пользователями
  - name: Messages
    description: Отправка и получение сообщений
  - name: Chats
    description: (Пока не используется)

components:
  schemas:
    # --- Модели для Auth ---
    TUserRegistrationRequest:
      type: object
      additionalProperties: false
      required: [user]
      properties:
        user:
          type: object
          additionalProperties: false
          required: [username, password, display_name]
          properties:
            username:
              type: string
              minLength: 3
              maxLength: 32
            password:
              type: string
              minLength: 8
              format: password
            display_name:
              type: string
              minLength: 3
              maxLength: 50
            biography:
              type: string
              maxLength: 180
    
    TUserRegistered:
      type: object
      properties:
        username:
          type: string
          example: alice
        token:
          type: string
          format: JWT
          example: 'eyJhbGciO.iJIUzI1NiIsI.nR5cCI6IkpXVCJ9'
    
    # --- Модели для Users ---
    TUserProfile:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          example: 'a1b2c3d4-e5f6-7890-1234-567890abcdef'
        username:
          type: string
          example: alice
        display_name:
          type: string
          example: 'Daniil Repin'
        biography:
          type: string
          example: "My biography"


    # --- Общая модель ошибки ---
    TError:
      type: object
      properties:
        code:
          type: string
          example: '400'
        message:
          type: string
          example: 'Неверное имя пользователя или пароль'
        details:
          type: object
          properties:  
            errors: 
                type: object
                description: Ошибки валидации по полям
                additionalProperties:
                  type: array
                  items:
                    type: string

  
paths:
  /users/register:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TUserRegistrationRequest'
      responses:
        '200':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TUserRegistered'
        '400':
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TError'
        '409':
          description: Пользователь с таким именем уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TError'

  /users/username/{username}:
    get:
      tags:
        - Users
      summary: Получение профиля пользователя по username
      operationId: getUserProfileByUsername
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Профиль получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TUserProfile'
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TError'

  /users/id/{user_id}:
    get:
      tags:
        - Users
      summary: Получение профиля пользователя по user_id
      description: Получить публичный профиль пользователя по его уникальному идентификатору.
      operationId: getUserProfileById
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Профиль получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TUserProfile'
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TError'



