openapi: 3.0.0
info:
  title: Chat API
  description: MVP чата-хаба на userver
  version: 1.0.0
servers:
  - url: /v1
    description: Основной шлюз API

tags:
  - name: Auth
    description: Аутентификация и регистрация
  - name: Users
    description: Управление пользователями
  - name: Messages
    description: Отправка и получение сообщений
  - name: Chats
    description: (Пока не используется)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Error
    Error:
      type: object
      properties:
        code:
          type: string
          example: "400"
        message:
          type: string
          example: "Неверное имя пользователя или пароль"
        details:
          type: object
          properties:
            errors:
              type: object
              description: Ошибки валидации по полям
              additionalProperties:
                type: array
                items:
                  type: string
    # Token
    AuthToken:
      type: object
      required:
        - access-token
      properties:
        access-token:
          type: string
          format: jwt
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

    # Users
    UserRegistrationRequest:
      type: object
      additionalProperties: false
      required: [user]
      properties:
        user:
          type: object
          additionalProperties: false
          required: [username, password, display_name]
          properties:
            username:
              type: string
              minLength: 3
              maxLength: 32
            password:
              type: string
              minLength: 8
              format: password
            display_name:
              type: string
              minLength: 3
              maxLength: 50
            biography:
              type: string
              maxLength: 180

    UserLoginRequest:
      type: object
      additionalProperties: false
      properties:
        user:
          type: object
          additionalProperties: false
          required: [username, password]
          properties:
            username:
              type: string
              minLength: 3
              maxLength: 32
            password:
              type: string
              minLength: 8
              format: password

    UserRegistered:
      type: object
      properties:
        username:
          type: string
          example: alice
        token:
          $ref: "#/components/schemas/AuthToken"
        
    UserLoggedIn:
      type: object
      properties:
        token:
          $ref: "#/components/schemas/AuthToken"

    UserProfile:
      type: object
      properties:
        username:
          type: string
          example: alice
        display_name:
          type: string
          example: "Daniil Repin"
        biography:
          type: string
          example: "My biography"

    UserUpdateRequest:
      type: object
      additionalProperties: false
      required: [user]
      properties:
        user:
          type: object
          additionalProperties: false
          properties:
            username:
              type: string
              minLength: 3
              maxLength: 32
            password:
              type: string
              minLength: 8
              format: password
            display_name:
              type: string
              minLength: 3
              maxLength: 50
            biography:
              type: string
              maxLength: 180
    
    # Messages
    SendMessageRequest:
      type: object
      description: Сообщение для отправки
      properties:
        message:
          type: object
          properties:
            recipient:
              type: string
              description: Username пользователя, которому отправляется сообщение
            payload:
              type: string
              description: Текст сообщения
              example: "Hello, World!"
          required:
            - recipient
            - payload

    Message:
      type: object
      required:
        - sender
        - text
      properties:
        sender:
          type: string
          description: Username пользователя-отправителя
          example: "user123"
        text:
          type: string
          description: Текст сообщения
          example: "Hello, World!"
      description: Сообщение

    PolledMessages:
      type: object
      required:
        - resync_required
      properties:
        resync_required:
          type: boolean
          description: Флаг необходимости ресинхронизации сообщений
          example: false
        messages:
          type: array
          description: Массив сообщений
          items:
            $ref: '#/components/schemas/Message'
          example:
            - sender: "alice"
              text: "First message"
            - sender: "bob"
              text: "Second message"
      description: Новые сообщения

    SessionParams:
      type: object
      required:
        - session_id
      properties:
        session_id:
          type: string
          description: ID сессии {gateway_id}-{sessiond_id}
          example: 2531-3847323
      description: Созданная сессия
      
paths:
  # Users
  /users/register:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
      responses:
        "200":
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegistered"
        "400":
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Пользователь с таким именем уже существует
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/login:
    post:
      tags:
        - Auth
      summary: Вход пользователя (получение токена)
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
      responses:
        "200":
          description: Успешный вход, токен выдан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserLoggedIn"
        "401":
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/username/{username}:
    get:
      tags:
        - Users
      summary: Получение профиля пользователя по username
      operationId: getUserProfileByUsername
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Профиль получен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      tags:
        - Users
      summary: Обновление профиля пользователя по username
      operationId: updateUserProfileByUsername
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequest"
      responses:
        "200":
          description: Профиль обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
        "400":
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Недостаточно прав
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Username уже занят
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - Users
      summary: Удаление пользователя по username
      operationId: deleteUserProfileByUsername
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Пользователь удален
        "401":
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Недостаточно прав
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  # Messages
  /messages/send:
    post:
      tags:
        - Messages
      summary: Отправить сообщение пользователю
      operationId: sendMessage
      security:
        - BearerAuth: []
      requestBody:
        description: Сообщение для отправки
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
      responses:
        "202":
          description: Сообщение принято к доставке
        "400":
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Не авторизован
        "404":
          description: Получатель не найден
        "409":
          description: Пользователь офлайн
        "413":
          description: "Слишком большой payload"


  /messages/poll/{session_id}:
    get:
      tags:
        - Messages
      summary: Получить сообщения пользователя
      operationId: pollMessages
      parameters:
        - name: session_id
          in: path
          required: true
          description: ID сессии пользователя
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Полученные сообщения
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolledMessages"
        "401":
          description: Не авторизован
        "409":
          description: У сессии уже есть активный consumer
        "410":
          description: Сессия неактивна

  /messages/poll/start:
    post:
      tags:
        - Messages
      summary: Открыть сессию поллинга
      operationId: startPolling
      security:
        - BearerAuth: []
      responses:
        "200":
          description: ID сессии
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionParams"
        "401":
          description: Не авторизован
        "429":
          description: Уже открыто максимальное количество сессий
        "503":
          description: Сервис временно недоступен
